services:
  postgres:
    image: postgres:13
    container_name: postgres-desafio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: desafio-banco-digital
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./banco-de-dados/script-banco-de-dados.sql:/docker-entrypoint-initdb.d/script-banco-de-dados.sql
    restart: unless-stopped

  contacorrente-api:
    build:
      context: ./src/ContaCorrente
      dockerfile: Dockerfile
    container_name: contacorrente-api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=desafio-banco-digital;Username=postgres;Password=desafio
    ports:
      - "5215:8080"
    restart: unless-stopped

  transferencia-api:
    build:
      context: ./src/Transferencia
      dockerfile: Dockerfile
    container_name: transferencia-api
    depends_on:
      - postgres
      - contacorrente-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=desafio-banco-digital;Username=postgres;Password=desafio
      Services__ContaCorrenteBaseUrl: http://contacorrente-api:8080
    ports:
      - "5216:8080"
    restart: unless-stopped
